In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

Creación de arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 5, 7, 10])
a

array([ 1,  2,  3,  5,  7, 10])

In [11]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 10])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Creación de arrays multi dimensionales

In [19]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [33]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [34]:
n[2] = [1, 1, 1]

In [35]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [36]:
n[:, 2]

array([3, 6, 1])

Creación de arrays aleatorios

In [41]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [46]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [47]:
np.random.seed(2)
np.random.randint(low=5, high=100, size=(5,2))

array([[45, 20],
       [77, 27],
       [48, 87],
       [80, 12],
       [39, 54]])

Operaciones de elemento a elemento

In [49]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [50]:
a + 1

array([1, 2, 3, 4, 5])

In [53]:
b = (10 + (a * 2)) ** 2 / 100

In [54]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

Operaciones de comparación

In [55]:
a

array([0, 1, 2, 3, 4])

In [56]:
a >= 2

array([False, False,  True,  True,  True])

In [57]:
a > b

array([False, False,  True,  True,  True])

In [58]:
a[a > b]

array([2, 3, 4])

Resumen de Operaciones

In [59]:
a

array([0, 1, 2, 3, 4])

In [60]:
a.mean()

np.float64(2.0)

In [61]:
a.std()

np.float64(1.4142135623730951)

In [63]:
n.min()

np.int64(1)

Operaciones con vectores

Suma

In [45]:
u = np.array([2, 3, 4, 6])
u

array([2, 3, 4, 6])

In [46]:
v = np.array([5, 6, 7, 9])
v

array([5, 6, 7, 9])

In [47]:
u + v

array([ 7,  9, 11, 15])

Multiplicación

In [48]:
u * v

array([10, 18, 28, 54])

In [49]:
v.shape[0]

4

In [50]:
def multiplicacion_de_vectores (u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range (n):
        result = result + u[i] * v[i]

    return result

In [51]:
multiplicacion_de_vectores (u, v)

np.float64(110.0)

In [52]:
u.dot(v)

np.int64(110)

Multiplicación de vector por matriz

In [53]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [54]:
U.shape[1]

4

In [55]:
def vector_por_matriz (U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = multiplicacion_de_vectores(U[i], v)
    
    return result

In [56]:
vector_por_matriz(U, v)

array([123.,  42.,  44.])

In [57]:
U.dot(v)

array([123,  42,  44])

Multiplicación de matriz por matriz

In [58]:
V = np.array([
    [2, 4, 5],
    [1, 2, 1],
    [3, 1, 2],
    [6, 8, 9],
])

In [59]:
def matriz_por_matriz(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = vector_por_matriz(U, vi)
        result[:, i] = Uvi

    return result

In [60]:
matriz_por_matriz(U, V)

array([[59., 69., 78.],
       [19., 25., 27.],
       [19., 24., 29.]])

Matriz de Identidad

In [65]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
V

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2],
       [6, 8, 9]])

In [67]:
V.dot(I)

array([[2., 4., 5.],
       [1., 2., 1.],
       [3., 1., 2.],
       [6., 8., 9.]])

Matriz Inversa

In [70]:
Vs = V[[0, 1, 2]]
Vs

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [71]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [72]:
Vs_inv.dot(Vs)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 2.77555756e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])